
name: Build Annie

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch/tag/commit to build"
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: windows-latest
    env:
      RUSTFLAGS: -Ctarget-feature=+crt-static
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-pc-windows-msvc
    steps:
      - name: Set ref
        run: |
          echo "REF=${{ inputs.ref || github.ref }}" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ env.REF }}

      - name: Print git status
        run: |
          git status

      - name: Set environment variables
        run: |
          echo "~/.cargo/bin" >> $GITHUB_PATH
          echo "SHA=$(git rev-parse $REF)" >> $GITHUB_ENV

      - name: Cache cargo registry and git trees
        uses: actions/cache@v3
        with:
          key: cargo-global-${{ runner.os }}
          path: |
            ~/.cargo/registry
            ~/.cargo/git

      - name: Install Rust via rustup
        run: |
          curl https://win.rustup.rs/ --silent --output rustup-init.exe
          ./rustup-init.exe -y --default-host=x86_64-pc-windows-msvc --profile=minimal
          rm rustup-init.exe

      - name: Update stable toolchain
        run: |
          rustup update stable

      - name: Install toolchain target
        run: |
          rustup target install ${{ matrix.target }}

      - name: Get rust toolchain SHA
        run: |
          echo "RUST_SHA=$(rustc -Vv | grep commit-hash | awk '{print $2}')" >> $GITHUB_ENV

      - name: Cache cargo build folder
        uses: actions/cache@v3
        with:
          key: cargo-target-dir-${{ env.SHA }}-${{ matrix.target }}-${{ env.RUST_SHA }}
          path: target

      - name: Run a full build
        run: |
          cargo +stable-${{ matrix.target }} build --release

      - name: Get package semver
        run: |
          cat Cargo.toml | sed -rn 's/^\s*version\s*=\s*"(.*?)"/SEMVER=\1/p' >> $GITHUB_ENV

      - name: Upload the built artifact
        uses: actions/upload-artifact@v3
        with:
          name: annie-${{ env.SEMVER }}-${{ matrix.target }}-${{ env.SHA }}
          path: |
            target/release/annie-am.exe
          retention-days: 7

      - name: Clear cargo cache
        run: |
          cargo install cargo-cache --no-default-features --features ci-autoclean
          cargo-cache
