
name: Build Annie

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch/tag/commit to build"
        required: true
        type: string
        default: master
      cargo-profile:
        description: "Cargo profile for build"
        required: true
        type: choice
        default: release
        options:
          - release-unoptimized
          - release-no-lto
          - release

jobs:
  build:
    name: Build
    runs-on: windows-latest
    env:
      RUSTFLAGS: -Ctarget-feature=+crt-static
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-pc-windows-msvc
    steps:
      - name: Install sccache
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          TAG=$(gh --repo mozilla/sccache release list | grep Latest | awk '{print $3}')
          gh --repo mozilla/sccache release download --pattern 'sccache-*-x86_64-pc-windows-msvc.tar.gz' $TAG
          tar -xf sccache-*.tar.gz
          mkdir -p ~/bin
          mv $(find -name sccache.exe) ~/bin/
          rm -rf sccache-*
          echo "SCCACHE_DIR=$(cygpath --windows ~/.sccache)" >> $GITHUB_ENV
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
          echo "~/bin" >> $GITHUB_PATH

      - name: Parse inputs
        run: |
          echo "REF=${{ inputs.ref || github.ref }}" >> $GITHUB_ENV
          echo "CARGO_PROFILE=${{ inputs.cargo-profile || 'release' }}" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ env.REF }}

      - name: Set environment variables
        run: |
          echo "~/.cargo/bin" >> $GITHUB_PATH
          echo "SHA=$(git rev-parse ${{ env.REF }})" >> $GITHUB_ENV

      - name: Cache cargo registry, git trees, and sccache
        uses: actions/cache@v3
        with:
          key: cargo-global-${{ runner.os }}
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.sccache

      - name: Install Rust via rustup
        run: |
          curl https://win.rustup.rs/ --silent --output rustup-init.exe
          ./rustup-init.exe -y --default-host=x86_64-pc-windows-msvc --profile=minimal
          rm rustup-init.exe

      - name: Update stable toolchain
        run: |
          rustup update stable

      - name: Install toolchain target
        run: |
          rustup target install ${{ matrix.target }}

      - name: Get rust toolchain SHA
        run: |
          echo "RUST_SHA=$(rustc -Vv | grep commit-hash | awk '{print $2}')" >> $GITHUB_ENV

      - name: Cache cargo build folder
        uses: actions/cache@v3
        with:
          key: cargo-target-dir-${{ env.SHA }}-${{ matrix.target }}-${{ env.RUST_SHA }}
          path: target

      - name: Run a full build
        run: |
          cargo +stable-${{ matrix.target }} build --profile=${{ env.CARGO_PROFILE }}

      - name: Get package semver
        run: |
          cat Cargo.toml | sed -rn 's/^\s*version\s*=\s*"(.*?)"/SEMVER=\1/p' >> $GITHUB_ENV

      - name: Upload the built artifact
        uses: actions/upload-artifact@v3
        with:
          name: annie-${{ env.SEMVER }}-${{ env.CARGO_PROFILE }}-${{ matrix.target }}-${{ env.SHA }}
          path: |
            target/${{ env.CARGO_PROFILE }}/annie-am.exe
          retention-days: 7

      - name: Clear cargo cache
        run: |
          cargo install cargo-cache --no-default-features --features ci-autoclean
          cargo-cache
