
name: Build Annie (MSVC)

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      target-ref:
        description: "Branch/tag/commit to build"
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: windows-latest
    env:
      RUSTFLAGS: -Ctarget-feature=+crt-static
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-pc-windows-msvc
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ inputs.target-ref }}
      - name: Print git status
        run: |
          git status
      - name: Create global cargo dirs
        run: |
          mkdir -p "~/.cargo/registry"
          mkdir -p "~/.cargo/git"
      - name: Set environment variables for the build
        run: |
          echo "~/.cargo/bin" >> $GITHUB_PATH
          echo "TARGET=${{ matrix.target }}" >> $GITHUB_ENV
      - name: Cache cargo registry and git trees
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Get rustc commit hash
        id: cargo-target-cache
        run: |
          echo "::set-output name=rust_hash::$(rustc -Vv | grep commit-hash | awk '{print $2}')"
        shell: bash
      - name: Cache cargo build
        uses: actions/cache@v2
        with:
          path: target
          key: ${{ github.base_ref }}-${{ github.head_ref }}-${{ matrix.target }}-cargo-target-dir-${{ steps.cargo-target-cache.outputs.rust_hash }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ github.base_ref }}-${{ matrix.target }}-cargo-target-dir-${{ steps.cargo-target-cache.outputs.rust_hash }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Rustup using win.rustup.rs
        run: |
          curl https://win.rustup.rs/ --silent --output rustup-init.exe
          ./rustup-init.exe -y --default-host=x86_64-pc-windows-msvc --profile=minimal
          rm rustup-init.exe
      - name: Ensure stable toolchain is up to date
        run: rustup update stable
      - name: Install the target
        run: rustup target install ${{ matrix.target }}
      - name: Run a full build
        run: cargo build --release
      - name: Upload the built artifact
        uses: actions/upload-artifact@v3
        with:
          name: annie-${{ github.sha }}
          path: |
            target/release/annie-am.exe
          retention-days: 7
      - name: Clear the cargo caches
        run: |
          cargo install cargo-cache --no-default-features --features ci-autoclean
          cargo-cache
